services:
    sylius.customer_order_addresses_saver:
        class: Magentix\SyliusPickupPlugin\Component\Core\Customer\CustomerOrderAddressesSaver
        public: true
        arguments:
            - "@sylius.customer_unique_address_adder"
    Magentix\SyliusPickupPlugin\Shipping\Service\Pickup\PickupHandlerResult:
        arguments:
            - "@sylius.repository.country"
    magentix_sylius_pickup_plugin.handler_result: "@Magentix\SyliusPickupPlugin\Shipping\Service\Pickup\PickupHandlerResult"
