services:
    Magentix\SyliusPickupPlugin\Controller\PickupController:
        public: true
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@magentix_sylius_pickup_plugin.handler_result"
        calls:
            -   setContainer: [ '@service_container' ]
