services:
    Magentix\SyliusPickupPlugin\Controller\PickupController:
        public: true
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@sylius.repository.country"
        calls:
            -   setContainer: [ '@service_container' ]
